### ISSUE TITLE
Comparing 6 and 7

### ISSUE THREAD

**Issue by djwrisley** [LLBeirut/llbeirut#10]
@kyraneth When we look at the images in 6.yml vs 7.yml are these to be coded as 1 paragraph or 2?

**Comment by djwrisley** [comment]
@kyraneth and check out 9.yml  Are there in fact 10 paragraphs?

**Comment by kyraneth** [comment]
I think 7.yml should be coded as 1 paragraph. 7.yaml can be construed as both, however I am inclined to encode it as one paragpraph, just because there is no semantic or linguistic basis for the split. 

I am indeed counting 10 paragraphs in 9.yaml, the split here is significant because only one of these paragphes contains multiple languages and scripts, and this is exactly the kind of feature we want to encode.
